repos:
  # Ruff for linting and formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.1
    hooks:
      # Run the linter
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      # Run the formatter
      - id: ruff-format

  # Skip Pylint for now due to configuration issues
  # - repo: local
  #   hooks:
  #     - id: pylint
  #       name: pylint
  #       entry: pylint
  #       language: system
  #       files: ^src/.*\.py$
  #       args: [--rcfile=.pylintrc]

  # Additional useful hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      # Basic file checks
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=1000']

      # Python-specific
      - id: check-ast
      - id: debug-statements
      - id: name-tests-test
        files: ^tests/.*\.py$

  # Additional Python checks
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black", "--line-length", "88"]

  # Skip security checks for now
  # - repo: https://github.com/PyCQA/bandit
  #   rev: '1.7.10'
  #   hooks:
  #     - id: bandit
  #       args: ['-r', 'src/']
  #       files: ^src/.*\.py$

# Configuration for pre-commit
default_stages: [pre-commit]
fail_fast: false
